spring:

  data:
    mongodb:
      #      database: webflux-mongo
      #      host: localhost
      #      port: 27017
      uri: mongodb://localhost:27017/mvc-mongo


server:
  servlet:
    contextPath: /
  port: 8083

logging:
  level:
    ROOT: info